server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/microservice_project1/config-server/config-repo
      fail-fast: false
      health:
        enabled: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env,metrics,prometheus

  endpoint:
    prometheus:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.cloud.config: DEBUG

info:
  app:
    name: ${spring.application.name}
    description: Centralized Configuration Server
    version: 1.0.0